INSERT INTO BIKETYPES (BIKETYPEDESCRIPTION)
VALUES ('VELO');

INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_DATE, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'VELO'));

INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL1', (SELECT BikeLotId FROM BIKELOTS));
INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL2', (SELECT BikeLotId FROM BIKELOTS));
INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL3', (SELECT BikeLotId FROM BIKELOTS));

