-- noinspection SqlWithoutWhereForFile
IF EXISTS (SELECT * FROM sys.FOREIGN_KEYS WHERE OBJECT_ID=OBJECT_ID(N'FK_VEHICLES_LOCKS')
    AND PARENT_OBJECT_ID = OBJECT_ID(N'VEHICLES'))
ALTER TABLE VEHICLES DROP CONSTRAINT FK_VEHICLES_LOCKS;

DELETE FROM RIDES;
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='VEHICLELOCATIONS') DELETE FROM VEHICLELOCATIONS;
DELETE FROM SUBSCRIPTIONS;
DELETE FROM USERS;
UPDATE LOCKS SET VEHICLEID=NULL;
DELETE FROM VEHICLES;
DELETE FROM LOCKS;
DELETE FROM STATIONS;
DELETE FROM BIKELOTS;

INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Velo Bike'));
INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Velo E-Bike'));
INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Step'));
INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Scooter'));

/*INSERT INTO BIKETYPES (BIKETYPEDESCRIPTION)
VALUES ('VELO');

INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL1', (SELECT BikeLotId FROM BIKELOTS));
INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL2', (SELECT BikeLotId FROM BIKELOTS));
INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL3', (SELECT BikeLotId FROM BIKELOTS));*/

