TRUNCATE TABLE RIDES;
TRUNCATE TABLE VEHICLELOCATIONS;
TRUNCATE TABLE SUBSCRIPTIONS;
TRUNCATE TABLE USERS;
TRUNCATE TABLE LOCKS;
TRUNCATE TABLE STATIONS;
TRUNCATE TABLE VEHICLES;
TRUNCATE TABLE BIKELOTS;

INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Velo Bike'));
INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Velo E-Bike'));
INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Step'));
INSERT INTO BIKELOTS (DELIVERYDATE, BIKETYPEID)
VALUES (CURRENT_TIMESTAMP, (SELECT BIKETYPEID FROM BIKETYPES WHERE BIKETYPEDESCRIPTION = 'Scooter'));

/*INSERT INTO BIKETYPES (BIKETYPEDESCRIPTION)
VALUES ('VELO');

INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL1', (SELECT BikeLotId FROM BIKELOTS));
INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL2', (SELECT BikeLotId FROM BIKELOTS));
INSERT INTO VEHICLES(SerialNumber, BikeLotId)
VALUES('SERIAL3', (SELECT BikeLotId FROM BIKELOTS));*/

